### ISSUE TITLE
Add ability to Search by EnumValue (similar to search by tag)

### ISSUE THREAD

**Issue by LorneCash** [ClausStolz/SmartEnums#15]
I have this enum (see below) and I need a way to lookup the enum from the Code's value so I can use the enum to get the Cluster's value.  It would be nice if this was a builtin feature like `FindByTag`.

I've found that I can do it like this:
`return SmartEnum.GetEnumerator<EventType>().Single(x => x.GetValueOf<string>("Code") == code);`
but it would be nice to have a simpler syntax that is an extension method (again like `FindByTag`).

```c#
public enum EventType
{
	[EnumValue("Code", "T")]
	[EnumValue("Cluster", 1)]
	Trade,

	[EnumValue("Code", "Q")]
	[EnumValue("Cluster", 1)]
	Quote,

	[EnumValue("Code", "A")]
	[EnumValue("Cluster", 2)]
	AggregatePerSecond,

	[EnumValue("Code", "AM")]
	[EnumValue("Cluster", 2)]
	AggregatePerMinute,

	[EnumValue("Code", "I")]
	[EnumValue("Cluster", 2)]
	Imbalance,

	[EnumValue("Code", "Status")]
	[EnumValue("Cluster", 0)]
	Status,
}
```

**Comment by ClausStolz** [comment]
I think you are right, there is not enough simplified syntax, I will look into it.
